### ISSUE TITLE
Fix Disease XML DTO properties

### ISSUE THREAD

**Issue by kirbykn** [imsweb/seerdata-utility#1]
Some of the property tags in the disease XML file are '&lt;string>' instead of the actual property name.

The fields in DiseaseXmlDto that have @XstreamImplicit also need to have the itemFieldName value specified.

**Comment by kirbykn** [comment]
@depryf The list of DiseaseXmlDto in DiseaseDataXmlDto doesn't have the itemFieldName value but the tag shows up correctly (I think because the DiseaseXmlDto specifies an XStreamAlias). Should I change the DiseaseDataXmlDto or leave it?

**Comment by depryf** [comment]
This issue only affected the collections of string and we decided to only fix those.  This has been fixed and merged.
